### ISSUE TITLE
Server doesn't see capitalized filename extensions

### ISSUE THREAD

**Issue by bencollinz** [OwenRay/Remote-MediaServer#127]
For example: it sees vacation.mp4 just fine. vacation2.MP4 cannot be found until you lowercase the extension.
Windows 10
latest beta of remote-mediaserver

**Comment by OwenRay** [comment]
Good point, for now you can work around it by modifying the settings.json (it should be in your home directory under .remote)
There you can modify the list of videoFileTypes to include MP4 as well
