### ISSUE TITLE
Fatal Node Crash on Setup

### ISSUE THREAD

**Issue by NathHorrigan** [OwenRay/Remote-MediaServer#23]
When running 'node setup.js', I get following error:
`
 Fatal error in ../deps/v8/src/api.cc, line 1062
 Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
==== C stack trace ===============================

    0   node                                0x0000000100bfad23 v8::base::debug::StackTrace::StackTrace() + 19
    1   node                                0x0000000100bf7ea9 V8_Fatal + 233
    2   node                                0x000000010014730a v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute) + 330
    3   binding.node                        0x00000001058c43f2 SassTypes::Boolean::get_constructor() + 352
    4   binding.node                        0x00000001058c630b SassTypes::Factory::initExports(v8::Local<v8::Object>) + 407
    5   node                                0x00000001009f5380 node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) + 859
    6   node                                0x00000001001797d1 v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 369
    7   node                                0x00000001001e75ac v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 924
    8   node                                0x00000001001e6a09 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 281
    9   ???                                 0x000039268c7843a7 0x0 + 62837728232359
    10  ???                                 0x000039268cb76146 0x0 + 62837732368710
`

Never come across this before, Have you experienced this problem?

**Comment by OwenRay** [comment]
Just to isolate the problem:
I think this happens when you run npm install in the frontend dir?
Could you also tell me what os+arch you're running.

**Comment by NathHorrigan** [comment]
OS: MacOS Sierra
Arch: i386 x86_64

**Comment by OwenRay** [comment]
At the moment I have no way of testing on osx,
I think it's a problem with compiling the sass binary
Could you confirm this happens when you run npm install in the frontend dir?

**Comment by OwenRay** [comment]
I have two ideas on how this may be fixed
Make sure to perform the commands in the frontend directory
 try:
npm i -g npm-check-updates
npm-check-updates -u
npm install

If that doesn't work try changing frontend/package.json line 35
From     "ember-cli-sass": "git://github.com/mike-north/ember-cli-sass.git#8ceb57d41f5774e8ececb5d1f05454449c19000c",
To     "ember-cli-sass": "3.1.0",
