### ISSUE TITLE
Start a gitter channel

### ISSUE THREAD

**Issue by NathHorrigan** [OwenRay/Remote-MediaServer#25]
Not an issue, But is possible to start a gitter channel or something similar for communication between contributors?

**Comment by OwenRay** [comment]
When I register a gitter account, I get an error:/
What do you think about slack?

**Comment by NathHorrigan** [comment]
Slack works for me 👍

**Comment by OwenRay** [comment]
https://remote-mediaserver.slack.com

**Comment by NathHorrigan** [comment]
I think you need to send an invite to my email?

**Comment by OwenRay** [comment]
I thought you would be able to request an invitation... Appearently not... that makes Slack.... suboptimal.
I managed to log in to gitter now... so.. change of plans;)
https://gitter.im/remote-mediaserver
