### ISSUE TITLE
Docker please

### ISSUE THREAD

**Issue by gerroon** [OwenRay/Remote-MediaServer#43]
Hi

Do you mind providing a docker image? Not all of us are js devs

thanks

**Comment by OwenRay** [comment]
Sure, will do so this week.

I also have native builds with NodeJS built in if you want to get started right away.
I just published those native builds under releases.

**Comment by gerroon** [comment]
Yeah native builds would work for me too, thanks for the work

**Comment by jkaberg** [comment]
An Docker image would for sure be highly appreciated, would also lower the bar quite a bit for people who'd like to try RMS out without installing a boatload of deps.

Make sure you setup an [automated build](https://docs.docker.com/docker-cloud/builds/automated-build/) 😄

**Comment by OwenRay** [comment]
Yeah, it's being worked on in [feature/docker](https://github.com/OwenRay/Remote-MediaServer/tree/feature/docker)
@Leopere kindly offered his assistance on that front:)

**Comment by Leopere** [comment]
Currently, there is a Docker branch available but I'm not sure if that'll be how it will be long term.  We've made progress to make the application stateless.  So that it takes very little to get the app running.  

I was thinking of focusing on a optimization for `docker-compose.yml` because it's the base for most production deployments.  Is there a goal you want to achieve with your deployment @jkaberg / @gerroon

**Comment by gerroon** [comment]
My goal is to be able to run and update painlessly, I am not a js dev so I personally do not want to deal with all this complicated dependencies, also this node stuff pollutes my system

**Comment by Leopere** [comment]
I definitely get the sentiments although from what I see at the moment RMS
doesn't really have many dependencies if you're in a rush. However it may
eventually want a few other things that will get included.

**Comment by jkaberg** [comment]
In the same boat as @gerroon really, I'd like to deploy it and use it. Obviously if its stateless that will be a big + long-term as some people might end up using it in clusters 🙈 

But I'm using docker-compose with some volumes etc. so aslong as it fits that I'm happy :-)

**Comment by Leopere** [comment]
This should be ready now, I didn't do a PR but @OwenRay merged the code from my fork and updated it to include the `guessit` container image as well so everything is truly self hosted.  This can be closed.

**Comment by OwenRay** [comment]
needed a little testing but I'm confident it should be working well now.
easiest way to set this up is just download the docker compose file and run docker-compose up
https://raw.githubusercontent.com/OwenRay/Remote-MediaServer/dev/docker-compose.yml
