### ISSUE TITLE
Unspecified type items are grouped together in library view

### ISSUE THREAD

**Issue by OwenRay** [OwenRay/Remote-MediaServer#46]
Media items which are part of a library of the type "Unspecified" are still grouped together on the library view. These should not be grouped or maybe grouped by directory?

**Comment by OwenRay** [comment]
@gerroon I implemented a grouping button on the library page. Would you mind checking if this works well for you?

**Comment by gerroon** [comment]
If you can make a release I will try it today

**Comment by OwenRay** [comment]
https://github.com/OwenRay/Remote-MediaServer/releases/tag/v0.1.1

**Comment by gerroon** [comment]
Am I suffering from the prev database? It seems to crash just when open the lib settings
```

koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md ../../../snapshot/Remote-MediaServer/backend/HttpServer.js:0:0
2018-12-11T23:05:08.930Z 'dht listening' { address: '0.0.0.0', family: 'IPv4', port: 8235 }
2018-12-11T23:05:08.935Z 'Server listening on: http://localhost:%s' 8234
(node:24085) UnhandledPromiseRejectionWarning: Error: spawn /media/DRIVE/opt/remotemediaserver/xdg-open ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1308:13)
    at startup (bootstrap_node.js:227:16)
    at bootstrap_node.js:648:3
(node:24085) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24085) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/snapshot/Remote-MediaServer/node_modules/moviedb-api/index.js:49
      if(response.ok) {
                  ^

TypeError: Cannot read property 'ok' of undefined
    at /snapshot/Remote-MediaServer/node_modules/moviedb-api/index.js:49:19
    at Request.callback (/snapshot/Remote-MediaServer/node_modules/moviedb-api/node_modules/superagent/lib/node/index.js:687:12)
    at ClientRequest.<anonymous> (/snapshot/Remote-MediaServer/node_modules/moviedb-api/node_modules/superagent/lib/node/index.js:639:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by OwenRay** [comment]
What's the library type? you can review those settings under ~/.remote/settings.json
it should be unspecified for home videos.

This error (#45) should still not occur of course but I will resolve this soon

**Comment by gerroon** [comment]
"type": "movie"

**Comment by OwenRay** [comment]
set the type to "" (which is "Unspecified") for home videos. (which I assume you want)

**Comment by gerroon** [comment]
sure I will try it

**Comment by gerroon** [comment]
I set to unspecified, same crash still happens. Let me know when you want me to test the fix.

**Comment by OwenRay** [comment]
Could you try deleting (or renaming) the ~/.remote/store (pretty sure this will resolve it, because the library types are stored in the media-item as well)

**Comment by gerroon** [comment]
It did not help

**Comment by OwenRay** [comment]
Does the machine have an active internet connection?

**Comment by gerroon** [comment]
It does but blocks quite a bit of stuff, moviedb might be blocked as well, need to see my logs. I do not need it myself.

**Comment by OwenRay** [comment]
ok, it's just that tmdb is also used to fetch available genres, I know you don't need that, as it stands it's part of the frontend filtering.
Just never realised there would be a use-case where those filter values weren't important;)

**Comment by gerroon** [comment]
Yeah, sorry I  did not make my use case clear enough I guess.

**Comment by OwenRay** [comment]
No no, not your fault, it's just my narrow focus on my own use case:P
I just committed a change that points the moviedb api to my repo (for the time being), I'll post the bins here once ready.

**Comment by OwenRay** [comment]
This should do it:
   Windows:  https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/win.zip
   MacOS:      https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/osx.zip
   Linux:         https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/linux.zip
   NPM:          https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/remote-mediaserver-0.1.1.tgz

**Comment by gerroon** [comment]
You were naive :)

```
(node:5734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/snapshot/Remote-MediaServer/node_modules/moviedb-api/index.js:49
      if(response.ok) {
                  ^

TypeError: Cannot read property 'ok' of undefined
    at /snapshot/Remote-MediaServer/node_modules/moviedb-api/index.js:49:19
    at Request.callback (/snapshot/Remote-MediaServer/node_modules/moviedb-api/node_modules/superagent/lib/node/index.js:687:12)
    at ClientRequest.<anonymous> (/snapshot/Remote-MediaServer/node_modules/moviedb-api/node_modules/superagent/lib/node/index.js:639:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by OwenRay** [comment]
what?... that should be impossible....

![image](https://user-images.githubusercontent.com/971553/49840761-1a7b5b80-fdb5-11e8-9ddd-5070fa3726bb.png)

I'll double check the build... but did already check them before posting...

**Comment by gerroon** [comment]
I will delete the whole binary folder and reisntall gimme a min

**Comment by gerroon** [comment]
Sorry you were right I was wrong, clean install fixed it., It does not crash and I made scan.

How do I manually scan though?

**Comment by OwenRay** [comment]
for now `/api/rescan`
you can also configure "Scan on restart" under settings.
normally it will detect changes automatically

**Comment by gerroon** [comment]
Ok thanks, I will give it a try. This looks really good. It would be nice to see the video titles in the library view mode, also list mode would be very helpful.

I will test it for awhile

**Comment by OwenRay** [comment]
Ok, will close this issue for now. feel free to create an issue if you find one, we also have a gitter if you want to chat/discuss things like titles (right now they appear on hover btw)
https://gitter.im/remote-mediaserver
