### ISSUE TITLE
it doesnt run on Node v12

### ISSUE THREAD

**Issue by sspilleman** [OwenRay/Remote-MediaServer#51]
Hi Owen,

Great work so far! It doesn't run on the latest Node though. I installed node via Homebrew. The current version is v12.3.1.

In order to make it work quite a few dependencies need to be updated (including manually installing modules lower down in the node-modules tree (all fs-events and chikodar stuff if I can recall what I all did to make it start).  Supercop  doesn't compile but can be replaced wth a pure javascript version (supercop.js).

Sander

**Comment by OwenRay** [comment]
Thnx for reporting the issue :)
I updated chokidar and unzip2, that fixed it for me, let me know if this works for you as well.
Here's a development build:
`npm install -g https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/remote-mediaserver-0.3.1.tgz`

**Comment by sspilleman** [comment]
Thanks, thats quick! I'll test it later and let you know.

**Comment by sspilleman** [comment]
> Thnx for reporting the issue :)
> I updated chokidar and unzip2, that fixed it for me, let me know if this works for you as well.
> Here's a development build:
> `npm install -g https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/remote-mediaserver-0.3.1.tgz`

Nope... fstream is also still using an older fs-events....

```
(node:9620) UnhandledPromiseRejectionWarning: ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/private/tmp/t/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/private/tmp/t/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/private/tmp/t/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
(node:9620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

There are some deprecation warnings installing your current version:

```
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```

**Comment by OwenRay** [comment]
Recently switched to yarn and it seems yarn does some subtle but important things a little differently. In short: this means you weren't testing the last version, sorry about that.
This should really work now;)
`npm install -g https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/remote-mediaserver-v0.3.1.tgz`
(note the url is not the same)

**Comment by sspilleman** [comment]
This one works!
