### ISSUE TITLE
Videos won't play in iOS (Safari AND Chrome)

### ISSUE THREAD

**Issue by sspilleman** [OwenRay/Remote-MediaServer#52]
Hi,

The subject says enough ;-)

Sander

**Comment by OwenRay** [comment]
🤔 It used to work, probably broke due to changes in safari or because of the offline support which uses hls as well

**Comment by sspilleman** [comment]
Ok.... Im not sure what exactly you mean by "offline support". Anything I could help with?

**Comment by OwenRay** [comment]
I recently added support for downloading media to your phone or dekstop so you can watch them offline. This involved some changes to the hls playback, I suspect safari doesn't like some of those changes. Not sure if you can help, eitherway I think I have a good idea where to look so I'll pick this up;)

**Comment by OwenRay** [comment]
Should now be fixed in the latest dev build
`npm install -g https://s3-eu-west-1.amazonaws.com/remote-mediaserver/dev/remote-mediaserver-v0.3.1.tgz`
plz reopen if you're still experiencing this issue
