### ISSUE TITLE
Mpeg4PlayHandler: Multiple Errors [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by sspilleman** [OwenRay/Remote-MediaServer#55]
When playing in Chrome (Mpeg4PlayHandler) I get quite a few errors like this:
```
  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
      at writeAfterEnd (_stream_writable.js:250:14)
      at PassThrough.Writable.write (_stream_writable.js:298:5)
      at Mpeg4PlayHandler.onData (/private/tmp/node_modules/remote-mediaserver/backend/modules/ffmpeg/Mpeg4PlayHandler.js:78:36)
      at Socket.emit (events.js:200:13)
      at Socket.Readable.read (_stream_readable.js:508:10)
      at flow (_stream_readable.js:977:34)
      at resume_ (_stream_readable.js:958:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:9)
```
After a few seconds AND when seeking.... res.onClose is trying to write?

**Comment by OwenRay** [comment]
The browser has already closed the connection and the server is still trying to write.
Probably some timing issue with reading from ffmpeg / writing to the browser while the connection has just closed.

RIght now this is not a big deal the error gets caught and the process keeps running fine. Low prio but an issue nonetheless.

**Comment by sspilleman** [comment]
Yes, I kinda figured that one out as well ;-)

Looking at Mpeg4PlayHandler is see:

this.ffmpeg.setOnClose(this.onClose.bind(this));
Looking at onClose function --> Youre setting  this.ffmpegEnded = true;

Then looking at onData function:
if you wrap the code in there with an 

> if(!this.ffmpegEnded) { }

 might do the trick? (you may still need to put the 

> this.context.body.end();

statement in the "else" branch in order to close the connection

**Comment by OwenRay** [comment]
I think it's the other way around,

**Comment by OwenRay** [comment]
I think it's the other way around, the browser connections is closed while ffmpeg is still sending,
```
    this.context.body.on('close', () => {
      this.ffmpeg.kill();
    });
```
after close gets called ffmpeg gets ended. This does not guarentee ffmpeg will stop immediately and it may empty it's buffers and send some last data.
There might be some function or variable to check if the context.body stream is close, otherwise we'll have to register the connection close and prevent any more writes.

**Comment by sspilleman** [comment]
You're absolutely right and agreed  I would still set a var and wrap the stuff in onData though to prevent the write...
