### ISSUE TITLE
Error playing particular mp4, forEach of undefined

### ISSUE THREAD

**Issue by dougmolineux** [OwenRay/Remote-MediaServer#62]
Thank you for this awesome project!

For some reason when playing an mp4 file, I was receiving this error in my terminal:

> (node:22956) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'forEach' of undefined

I was able to trace it down to line 74 of backend/modules/ffmpeg/MediaContentApiHandler.js

`streams` variable was undefined. I’m not sure why `await FFProbe.getInfo(this.filePath).streams;` would be returning undefined. Also, it doesn’t seem to happen to every mp4, I have an mp4 which works.

I would be happy to investigate this, so I've forked the project, to see if I can help fix it.

**Comment by OwenRay** [comment]
Thank you for the help.
I'd start by checking the file contents with ffprobe.
feel free to join the discord server if you have any questions regarding the codebase or anything else.
